package com.T2V.simple_expense_tracker.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf
import com.T2V.simple_expense_tracker.domain.repository.AppLanguage

data class AppStrings(
    val appName: String,
    val settings: String,
    val settingsTitle: String,
    val language: String,
    val theme: String,
    val appInterface: String,
    val dashboard: String,
    val ledger: String,
    val vietnamese: String,
    val english: String,
    val chinese: String,
    val russian: String,
    val japanese: String,
    val close: String,
    val selected: String,
    val recentTransactions: String,
    val noTransactionsToday: String,
    val detailList: String,
    val selectDate: String,
    val noTransactionsDay: String,
    val spendingStats: String,
    val statsCustomization: String,
    val chartBar: String,
    val chartLine: String,
    val income: String,
    val expense: String,
    val netSurplus: String,
    val netDeficit: String,
    val netBalance: String,
    val noStatsData: String,
    val filterTimePeriod: String,
    val periodDay: String,
    val periodWeek: String,
    val periodMonth: String,
    val periodYear: String,
    val statsDaysList: String,
    val statsWeeksList: String,
    val statsMonthsList: String,
    val statsYearsList: String,
    val add: String,
    val selectMonthYear: String,
    val prevYear: String,
    val nextYear: String,
    val selectYear: String,
    val unknownCounterparty: String,
    val totalBalance: String,
    val viewAccounts: String,
    val notificationList: String,
    val noNotifications: String,
    val sourceSmsGateway: String,
    val statusProcessed: String,
    val statusUnparsed: String,
    val payloadLabel: String
)

val VietnameseStrings = AppStrings(
    appName = "Simple Expense Tracker",
    settings = "Tùy chỉnh",
    settingsTitle = "Cài đặt",
    language = "Ngôn ngữ",
    theme = "Chọn Theme",
    appInterface = "Giao diện",
    dashboard = "Tổng quan",
    ledger = "Sổ thu chi",
    vietnamese = "Tiếng Việt",
    english = "Tiếng Anh",
    chinese = "Tiếng Trung",
    russian = "Tiếng Nga",
    japanese = "Tiếng Nhật",
    close = "Đóng",
    selected = "Đã chọn",
    recentTransactions = "Giao dịch gần đây",
    noTransactionsToday = "Chưa có giao dịch nào diễn ra hôm nay.",
    detailList = "Danh sách chi tiết",
    selectDate = "Chọn ngày",
    noTransactionsDay = "Không có giao dịch nào trong ngày này.",
    spendingStats = "Thống kê chi tiêu",
    statsCustomization = "Tùy chỉnh thống kê",
    chartBar = "Biểu đồ trụ",
    chartLine = "Biểu đồ đường",
    income = "Thu nhập",
    expense = "Chi tiêu",
    netSurplus = "Dư",
    netDeficit = "Thâm hụt",
    netBalance = "ròng:",
    noStatsData = "Chưa có dữ liệu thống kê",
    filterTimePeriod = "KHOẢNG THỜI GIAN",
    periodDay = "Ngày",
    periodWeek = "Tuần",
    periodMonth = "Tháng",
    periodYear = "Năm",
    statsDaysList = "CÁC NGÀY CẦN THỐNG KÊ",
    statsWeeksList = "CÁC TUẦN CẦN THỐNG KÊ",
    statsMonthsList = "CÁC THÁNG CẦN THỐNG KÊ",
    statsYearsList = "CÁC NĂM CẦN THỐNG KÊ",
    add = "Thêm",
    selectMonthYear = "Chọn Tháng & Năm",
    prevYear = "Năm trước",
    nextYear = "Năm sau",
    selectYear = "Chọn Năm",
    unknownCounterparty = "Không xác định",
    totalBalance = "Tổng số dư",
    viewAccounts = "Xem tài khoản",
    notificationList = "Danh sách thông báo",
    noNotifications = "Chưa có thông báo nào",
    sourceSmsGateway = "NGUỒN: SMS GATEWAY",
    statusProcessed = "ĐÃ XỬ LÝ",
    statusUnparsed = "CHƯA PHÂN TÍCH",
    payloadLabel = "NỘI DUNG:"
)

val EnglishStrings = AppStrings(
    appName = "Simple Expense Tracker",
    settings = "Settings",
    settingsTitle = "Settings",
    language = "Language",
    theme = "Select Theme",
    appInterface = "Interface",
    dashboard = "Dashboard",
    ledger = "Ledger",
    vietnamese = "Vietnamese",
    english = "English",
    chinese = "Chinese",
    russian = "Russian",
    japanese = "Japanese",
    close = "Close",
    selected = "Selected",
    recentTransactions = "Recent Transactions",
    noTransactionsToday = "No transactions today.",
    detailList = "Detail List",
    selectDate = "Select Date",
    noTransactionsDay = "No transactions on this day.",
    spendingStats = "Spending Stats",
    statsCustomization = "Customize Stats",
    chartBar = "Bar Chart",
    chartLine = "Line Chart",
    income = "Income",
    expense = "Expense",
    netSurplus = "Surplus",
    netDeficit = "Deficit",
    netBalance = "net:",
    noStatsData = "No statistical data available",
    filterTimePeriod = "TIME PERIOD",
    periodDay = "Day",
    periodWeek = "Week",
    periodMonth = "Month",
    periodYear = "Year",
    statsDaysList = "DAYS TO STATS",
    statsWeeksList = "WEEKS TO STATS",
    statsMonthsList = "MONTHS TO STATS",
    statsYearsList = "YEARS TO STATS",
    add = "Add",
    selectMonthYear = "Select Month & Year",
    prevYear = "Previous Year",
    nextYear = "Next Year",
    selectYear = "Select Year",
    unknownCounterparty = "Unknown",
    totalBalance = "Total Balance",
    viewAccounts = "View Accounts",
    notificationList = "Notification List",
    noNotifications = "No notifications",
    sourceSmsGateway = "SOURCE: SMS GATEWAY",
    statusProcessed = "PROCESSED",
    statusUnparsed = "UNPARSED",
    payloadLabel = "PAYLOAD:"
)

val JapaneseStrings = AppStrings(
    appName = "シンプル支出トラッカー",
    settings = "設定",
    settingsTitle = "設定",
    language = "言語",
    theme = "テーマを選択",
    appInterface = "インターフェース",
    dashboard = "ダッシュボード",
    ledger = "台帳",
    vietnamese = "ベトナム語",
    english = "英語",
    chinese = "中国語",
    russian = "ロシア語",
    japanese = "日本語",
    close = "閉じる",
    selected = "選択済み",
    recentTransactions = "最近の取引",
    noTransactionsToday = "今日の取引はありません。",
    detailList = "詳細リスト",
    selectDate = "日付を選択",
    noTransactionsDay = "この日の取引はありません。",
    spendingStats = "支出統計",
    statsCustomization = "統計をカスタマイズ",
    chartBar = "棒グラフ",
    chartLine = "折れ線グラフ",
    income = "収入",
    expense = "支出",
    netSurplus = "剰余",
    netDeficit = "不足",
    netBalance = "純額:",
    noStatsData = "統計データがありません",
    filterTimePeriod = "期間",
    periodDay = "日",
    periodWeek = "週",
    periodMonth = "月",
    periodYear = "年",
    statsDaysList = "統計対象の日",
    statsWeeksList = "統計対象の週",
    statsMonthsList = "統計対象の月",
    statsYearsList = "統計対象の年",
    add = "追加",
    selectMonthYear = "月と年を選択",
    prevYear = "前の年",
    nextYear = "次の年",
    selectYear = "年を選択",
    unknownCounterparty = "不明",
    totalBalance = "総残高",
    viewAccounts = "口座を表示",
    notificationList = "通知リスト",
    noNotifications = "通知はありません",
    sourceSmsGateway = "ソース: SMS ゲートウェイ",
    statusProcessed = "処理済み",
    statusUnparsed = "未解析",
    payloadLabel = "ペイロード:"
)

val RussianStrings = AppStrings(
    appName = "Простой трекер расходов",
    settings = "Настройки",
    settingsTitle = "Настройки",
    language = "Язык",
    theme = "Выбрать тему",
    appInterface = "Интерфейс",
    dashboard = "Панель управления",
    ledger = "Книга учета",
    vietnamese = "Вьетнамский",
    english = "Английский",
    chinese = "Китайский",
    russian = "Русский",
    japanese = "Японский",
    close = "Закрыть",
    selected = "Выбрано",
    recentTransactions = "Последние транзакции",
    noTransactionsToday = "Сегодня транзакций не было.",
    detailList = "Детальный список",
    selectDate = "Выбрать дату",
    noTransactionsDay = "В этот день не было транзакций.",
    spendingStats = "Статистика расходов",
    statsCustomization = "Настроить статистику",
    chartBar = "Столбчатая диаграмма",
    chartLine = "Линейная диаграмма",
    income = "Доходы",
    expense = "Расходы",
    netSurplus = "Профицит",
    netDeficit = "Дефицит",
    netBalance = "чистый:",
    noStatsData = "Нет статистических данных",
    filterTimePeriod = "ПЕРИОД ВРЕМЕНИ",
    periodDay = "День",
    periodWeek = "Неделя",
    periodMonth = "Месяц",
    periodYear = "Год",
    statsDaysList = "ДНИ ДЛЯ СТАТИСТИКИ",
    statsWeeksList = "НЕДЕЛИ ДЛЯ СТАТИСТИКИ",
    statsMonthsList = "МЕСЯЦЫ ДЛЯ СТАТИСТИКИ",
    statsYearsList = "ГОДЫ ДЛЯ СТАТИСТИКИ",
    add = "Добавить",
    selectMonthYear = "Выбрать месяц и год",
    prevYear = "Предыдущий год",
    nextYear = "Следующий год",
    selectYear = "Выбрать год",
    unknownCounterparty = "Неизвестно",
    totalBalance = "Общий баланс",
    viewAccounts = "Посмотреть счета",
    notificationList = "Список уведомлений",
    noNotifications = "Уведомлений нет",
    sourceSmsGateway = "ИСТОЧНИК: SMS-ШЛЮЗ",
    statusProcessed = "ОБРАБОТАНО",
    statusUnparsed = "НЕ РАСПАРСЕНО",
    payloadLabel = "ДАННЫЕ:"
)

val ChineseStrings = AppStrings(
    appName = "简单支出追踪器",
    settings = "设置",
    settingsTitle = "设置",
    language = "语言",
    theme = "选择主题",
    appInterface = "界面",
    dashboard = "仪表板",
    ledger = "账本",
    vietnamese = "越南语",
    english = "英语",
    chinese = "中文",
    russian = "俄语",
    japanese = "日语",
    close = "关闭",
    selected = "已选择",
    recentTransactions = "最近交易",
    noTransactionsToday = "今天还没有交易。",
    detailList = "详细列表",
    selectDate = "选择日期",
    noTransactionsDay = "这一天没有交易。",
    spendingStats = "支出统计",
    statsCustomization = "自定义统计",
    chartBar = "柱状图",
    chartLine = "折线图",
    income = "收入",
    expense = "支出",
    netSurplus = "盈余",
    netDeficit = "赤字",
    netBalance = "净额:",
    noStatsData = "暂无统计数据",
    filterTimePeriod = "时间段",
    periodDay = "日",
    periodWeek = "周",
    periodMonth = "月",
    periodYear = "年",
    statsDaysList = "需要统计的日期",
    statsWeeksList = "需要统计的周",
    statsMonthsList = "需要统计的月",
    statsYearsList = "需要统计的年",
    add = "添加",
    selectMonthYear = "选择月份和年份",
    prevYear = "上一年",
    nextYear = "下一年",
    selectYear = "选择年份",
    unknownCounterparty = "未知",
    totalBalance = "总余额",
    viewAccounts = "查看账户",
    notificationList = "通知列表",
    noNotifications = "暂无通知",
    sourceSmsGateway = "来源: SMS 閘道",
    statusProcessed = "已处理",
    statusUnparsed = "未解析",
    payloadLabel = "负载:"
)

val LocalAppStrings = staticCompositionLocalOf<AppStrings> {
    error("No AppStrings provided")
}

fun getAppStringsForLanguage(language: AppLanguage): AppStrings {
    return when (language) {
        AppLanguage.VIETNAMESE -> VietnameseStrings
        AppLanguage.ENGLISH -> EnglishStrings
        AppLanguage.JAPANESE -> JapaneseStrings
        AppLanguage.RUSSIAN -> RussianStrings
        AppLanguage.CHINESE -> ChineseStrings
    }
}
