package com.T2V.simple_expense_tracker.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

enum class AppTheme(
    val colorScheme: ColorScheme,
    val themeName: String,
    val isDark: Boolean
) {
    EMERALD(
        colorScheme = darkColorScheme(
            primary = DarkBluePrimary,
            onPrimary = DarkBlueOnPrimary,
            primaryContainer = DarkBluePrimaryContainer,
            onPrimaryContainer = DarkBlueOnPrimaryContainer,
            secondary = DarkBlueSecondary,
            onSecondary = DarkBlueOnSecondary,
            secondaryContainer = DarkBlueSecondaryContainer,
            onSecondaryContainer = DarkBlueOnSecondaryContainer,
            tertiary = DarkBlueTertiary,
            onTertiary = DarkBlueOnTertiary,
            tertiaryContainer = DarkBlueTertiaryContainer,
            onTertiaryContainer = DarkBlueOnTertiaryContainer,
            background = DarkBlueBackground,
            onBackground = DarkBlueOnBackground,
            surface = DarkBlueSurface,
            onSurface = DarkBlueOnSurface,
            surfaceVariant = DarkBlueSurfaceVariant,
            onSurfaceVariant = DarkBlueOnSurfaceVariant,
            surfaceTint = DarkBlueSurfaceTint,
            error = Error,
            onError = OnError,
            errorContainer = ErrorContainer,
            onErrorContainer = OnErrorContainer,
            outline = Outline,
            outlineVariant = OutlineVariant
        ),
        themeName = "Emerald",
        isDark = true
    ),
    OCEAN(
        colorScheme = lightColorScheme(
            primary = OceanPrimary,
            onPrimary = OceanOnPrimary,
            primaryContainer = OceanPrimaryContainer,
            onPrimaryContainer = OceanOnPrimaryContainer,
            secondary = OceanSecondary,
            onSecondary = OceanOnSecondary,
            secondaryContainer = OceanSecondaryContainer,
            onSecondaryContainer = OceanOnSecondaryContainer,
            tertiary = OceanTertiary,
            onTertiary = OceanOnTertiary,
            tertiaryContainer = OceanTertiaryContainer,
            onTertiaryContainer = OceanOnTertiaryContainer,
            background = OceanLightBackground,
            onBackground = OceanLightOnBackground,
            surface = OceanLightSurface,
            onSurface = OceanLightOnSurface,
            surfaceVariant = OceanSurfaceVariant,
            onSurfaceVariant = OceanOnSurfaceVariant,
            surfaceTint = OceanSurfaceTint,
            error = Error,
            onError = OnError,
            errorContainer = ErrorContainer,
            onErrorContainer = OnErrorContainer,
            outline = Outline,
            outlineVariant = OutlineVariant
        ),
        themeName = "Ocean",
        isDark = false
    ),
    FOREST(
        colorScheme = lightColorScheme(
            primary = ForestPrimary,
            onPrimary = ForestOnPrimary,
            primaryContainer = ForestPrimaryContainer,
            onPrimaryContainer = ForestOnPrimaryContainer,
            secondary = ForestSecondary,
            onSecondary = ForestOnSecondary,
            secondaryContainer = ForestSecondaryContainer,
            onSecondaryContainer = ForestOnSecondaryContainer,
            tertiary = ForestTertiary,
            onTertiary = ForestOnTertiary,
            tertiaryContainer = ForestTertiaryContainer,
            onTertiaryContainer = ForestOnTertiaryContainer,
            background = ForestLightBackground,
            onBackground = ForestLightOnBackground,
            surface = ForestLightSurface,
            onSurface = ForestLightOnSurface,
            surfaceVariant = ForestSurfaceVariant,
            onSurfaceVariant = ForestOnSurfaceVariant,
            surfaceTint = ForestSurfaceTint,
            error = Error,
            onError = OnError,
            errorContainer = ErrorContainer,
            onErrorContainer = OnErrorContainer,
            outline = Outline,
            outlineVariant = OutlineVariant
        ),
        themeName = "Forest",
        isDark = false
    ),
    SUNSET(
        colorScheme = darkColorScheme(
            primary = SunsetPrimary,
            onPrimary = SunsetOnPrimary,
            primaryContainer = SunsetPrimaryContainer,
            onPrimaryContainer = SunsetOnPrimaryContainer,
            secondary = SunsetSecondary,
            onSecondary = SunsetOnSecondary,
            secondaryContainer = SunsetSecondaryContainer,
            onSecondaryContainer = SunsetOnSecondaryContainer,
            tertiary = SunsetTertiary,
            onTertiary = SunsetOnTertiary,
            tertiaryContainer = SunsetTertiaryContainer,
            onTertiaryContainer = SunsetOnTertiaryContainer,
            background = SunsetBackground,
            onBackground = SunsetOnBackground,
            surface = SunsetSurface,
            onSurface = SunsetOnSurface,
            surfaceVariant = SunsetSurfaceVariant,
            onSurfaceVariant = SunsetOnSurfaceVariant,
            surfaceTint = SunsetSurfaceTint,
            error = Error,
            onError = OnError,
            errorContainer = ErrorContainer,
            onErrorContainer = OnErrorContainer,
            outline = Outline,
            outlineVariant = OutlineVariant
        ),
        themeName = "Sunset",
        isDark = true
    ),
    CANDY(
        colorScheme = lightColorScheme(
            primary = CandyPrimary,
            onPrimary = CandyOnPrimary,
            primaryContainer = CandyPrimaryContainer,
            onPrimaryContainer = CandyOnPrimaryContainer,
            secondary = CandySecondary,
            onSecondary = CandyOnSecondary,
            secondaryContainer = CandySecondaryContainer,
            onSecondaryContainer = CandyOnSecondaryContainer,
            tertiary = CandyTertiary,
            onTertiary = CandyOnTertiary,
            tertiaryContainer = CandyTertiaryContainer,
            onTertiaryContainer = CandyOnTertiaryContainer,
            background = CandyLightBackground,
            onBackground = CandyLightOnBackground,
            surface = CandyLightSurface,
            onSurface = CandyLightOnSurface,
            surfaceVariant = CandySurfaceVariant,
            onSurfaceVariant = CandyOnSurfaceVariant,
            surfaceTint = CandySurfaceTint,
            error = Error,
            onError = OnError,
            errorContainer = ErrorContainer,
            onErrorContainer = OnErrorContainer,
            outline = Outline,
            outlineVariant = OutlineVariant
        ),
        themeName = "Candy",
        isDark = false
    ),
    LUXURY(
        colorScheme = darkColorScheme(
            primary = LuxuryPrimary,
            onPrimary = LuxuryOnPrimary,
            primaryContainer = LuxuryPrimaryContainer,
            onPrimaryContainer = LuxuryOnPrimaryContainer,
            secondary = LuxurySecondary,
            onSecondary = LuxuryOnSecondary,
            secondaryContainer = LuxurySecondaryContainer,
            onSecondaryContainer = LuxuryOnSecondaryContainer,
            tertiary = LuxuryTertiary,
            onTertiary = LuxuryOnTertiary,
            tertiaryContainer = LuxuryTertiaryContainer,
            onTertiaryContainer = LuxuryOnTertiaryContainer,
            background = LuxuryBackground,
            onBackground = LuxuryOnBackground,
            surface = LuxurySurface,
            onSurface = LuxuryOnSurface,
            surfaceVariant = LuxurySurfaceVariant,
            onSurfaceVariant = LuxuryOnSurfaceVariant,
            surfaceTint = LuxurySurfaceTint,
            error = Error,
            onError = OnError,
            errorContainer = ErrorContainer,
            onErrorContainer = OnErrorContainer,
            outline = Outline,
            outlineVariant = OutlineVariant
        ),
        themeName = "Luxury",
        isDark = true
    ),
    MINIMAL(
        colorScheme = lightColorScheme(
            primary = MinimalPrimary,
            onPrimary = MinimalOnPrimary,
            primaryContainer = MinimalPrimaryContainer,
            onPrimaryContainer = MinimalOnPrimaryContainer,
            secondary = MinimalSecondary,
            onSecondary = MinimalOnSecondary,
            secondaryContainer = MinimalSecondaryContainer,
            onSecondaryContainer = MinimalOnSecondaryContainer,
            tertiary = MinimalTertiary,
            onTertiary = MinimalOnTertiary,
            tertiaryContainer = MinimalTertiaryContainer,
            onTertiaryContainer = MinimalOnTertiaryContainer,
            background = MinimalLightBackground,
            onBackground = MinimalLightOnBackground,
            surface = MinimalLightSurface,
            onSurface = MinimalLightOnSurface,
            surfaceVariant = MinimalSurfaceVariant,
            onSurfaceVariant = MinimalOnSurfaceVariant,
            surfaceTint = MinimalSurfaceTint,
            error = Error,
            onError = OnError,
            errorContainer = ErrorContainer,
            onErrorContainer = OnErrorContainer,
            outline = Outline,
            outlineVariant = OutlineVariant
        ),
        themeName = "Minimal",
        isDark = false
    )
}